Develop
JeanPaulYps/marvel-comics pull request #2
Opened 2021-10-26 21:05 UTC by JeanPaulYps

### Creacion del componente LastComics

Este componente se encarga de mostrar los comics en el home de la pagina web

2021-11-02 17:56 UTC, amautave requested changes
Sólo me queda una duda respecto a la carpeta `containers`... es la misma que `components`? Tienen el mismo objetivo?

2021-11-02 17:56 UTC, amautave commented on src/containers/ComicItem.jsx
> +        <div>
Este div lo puedes borrar, ya tienes uno interno que envuelve el componente. No es necesario meter un nivel más.

2021-11-02 17:56 UTC, amautave commented on src/containers/ComicItem.jsx
> +export { ComicItem, };
End Of File, tienes que meterle un salto de línea al final.

2021-11-02 17:56 UTC, amautave commented on src/containers/Loader.jsx
> +function Loader() {
Aquí puedes usar un arrow function y te queda más sencillo. Algo como:
`const Loader = () => <div className="lds-hourglass"></div>;`

2021-11-02 17:56 UTC, amautave commented on src/containers/Loader.jsx
> +export {Loader, };
EOF

2021-11-02 17:56 UTC, amautave commented on src/containers/index.js
> +export { Loader } from './Loader';
EOF

2021-11-02 17:56 UTC, amautave commented on src/pages/LastComics.jsx
> +    },[dispatch])
Generalmente estos selectores y el getData se hacen en otro archivo, puede ser en un index de la página o del componente, con el fin de que el componente sólo reciba props y más adelante sea más sencillo probar. También así se separan responsabilidades. Por ahora no creo necesario moverlo, pero para que lo tengas en cuenta.

2021-11-02 17:56 UTC, amautave commented on src/pages/LastComics.jsx
> +        <div>
Este `div`  también se puede borrar.

2021-11-02 17:56 UTC, amautave commented on src/services/index.js
> +export { marvelFetch } from './marvelFetch';
EOF

2021-11-02 17:56 UTC, amautave commented on src/services/lastComicsFetch.js
> +export { fetchLastComics, }
EOF

2021-11-02 17:56 UTC, amautave commented on src/services/marvelFetch.js
> +const PRIVATE_KEY = process.env.REACT_APP_PRIVATE_KEY;
Pasar secrets por variables de entorno es excelente! 👍

2021-11-02 17:56 UTC, amautave commented on src/services/marvelFetch.js
> +export {marvelFetch, };
EOF

2021-11-02 17:56 UTC, amautave commented on src/services/marvelFetch.js
> +const marvelFetch = async (route, additionalParameters) => {
Buena abstracción 👍

2021-11-02 17:56 UTC, amautave commented on src/store/configureStore.js
> +export {store, }
EOF

2021-11-02 17:56 UTC, amautave commented on src/store/lastComics.js
> +}
Este método lo puedes escribir un poco más claro usando `map`, algo como:
`const filterComicAttributesToShow = (comics)  => comics.map((comic) => { [Aquí retornas el nuevo elemento modificado] })`

2021-11-02 17:56 UTC, amautave commented on src/store/lastComics.js
> +export {lastComics, fetchLastComics};
EOF

2021-11-02 17:56 UTC, amautave commented on src/styles/ComicItem.css
> +}
EOF

2021-11-02 17:56 UTC, amautave commented on src/styles/Loader.css
> +
EOF

2021-11-02 21:55 UTC, JeanPaulYps commented
Se ha creado un nuevo Pull Request que corrige _casi todos los comentarios anteriores_. Ademas se agrega la funcionalidad del carrito de compra y una vista de checkout donde se pueden ver los comics que estan en el carrito.

2021-11-04 14:25 UTC, amautave commented on src/components/ComicItem.jsx
> +        }
Si la key del objeto se va a llamar igual que la variable que tienes para el valor, no es necesario especificar key: value, puedes dejarlo así: `const comicAttributes = { id, coverURL, title, creatorName, price };`.

2021-11-04 14:25 UTC, amautave commented on src/components/Layout.jsx
> +        <>
Bien! utilizando fragments

2021-11-04 14:25 UTC, amautave commented on src/components/Layout.jsx
> +export { Layout, }
EOF

2021-11-05 19:49 UTC, amautave approved these changes

2021-11-10 00:06 UTC, merged